title: life
description: The site with documentations of my life. Hobbies, Tech, Places and More!
exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
keep_files:
- images
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  imagesdir: /images
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=pygments
    - pygments-css=style
    - icons=font
    - iconsdir=/images/icons
    - stem
